# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: ideashaper_production
  username: standardcode  
  password: codeisstandard
  host: standardcode.c61h6tst4tky.us-east-1.rds.amazonaws.com
  port: 3306

 